name: Hexo Deploy

on:
  push:
    branches:
      - master

env:
  HEXO_ALGOLIA_INDEXING_KEY: fa20b2f5079dd134f1da83def9171ac4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Checkout Hexo
        uses: actions/checkout@v2
      - name: Checkout Theme
        uses: actions/checkout@v2
        with:
          repository: theme-next/hexo-theme-next
          ref: master
          path: themes/next

      - name: Setup Hexo
        run: |
          cp -r patch/next themes/next
          npm install hexo-cli gulp-cli -g
          npm install
          hexo clean
          hexo algolia
          hexo generate
          gulp

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: public
